version: '3.8'

services:
  wg-slim:
    image: ghcr.io/phasip/wg-slim:latest
    pull_policy: never
    ports:
      - "51820:51820/udp"
      - "5000:5000/tcp"
    environment:
      INITIAL_CONFIG: |
        basic:
          bind_addr: "5000"
        server:
          interface_name: wg0
      CONFIG_FILE: "/data/wg-slim.yaml"
    volumes:
      - ./data:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped